#==============================================================================
# Personal `SpaceVim` see: (http://spacevim.org) custom (toml) configuration
# Name: Mick Clarke (avastmick)
# Date: February 2019
#==============================================================================
# "Zen" mode
[[custom_plugins]]
  name = "junegunn/goyo.vim"
# Transparent background
[[custom_plugins]]
  name = "miyakogi/seiya.vim"
[[custom_plugins]]
  name = "cespare/vim-toml"
# The following is an alternative (light) RLS plugin set
# Works okay and doesn't get in the way, but isn't full featured.
# The Spacevim built-in layer often fails - see below
# [[custom_plugins]]
  # name = 'prabirshrestha/async.vim'
# [[custom_plugins]]
  # name = 'prabirshrestha/vim-lsp'
# [[custom_plugins]]
  # name = 'prabirshrestha/asyncomplete.vim'
# [[custom_plugins]]
  # name = 'prabirshrestha/asyncomplete-lsp.vim'

# All SpaceVim option below [option] section
[options]
    enable_debug = false
    colorscheme = "gruvbox"
    background = "dark"

    enable_guicolors = true
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    enable_statusline_display_mode = false
    enable_os_fileformat_icon = true

    # vimfiler options
    enable_vimfiler_welcome = false
    enable_vimfiler_gitstatus = true
    enable_vimfiler_filetypeicon = false

    realtime_leader_guide = true
    
    buffer_index_type = true
    buffer_index_type = 4

    # Load in the user specific configuration
    #   - see ~/.SpaceVim.d/autoload/myspacevim.vim
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"
[[layers]]
  name = "shell"
  default_position = 'bottom'
  default_height = 30
[[layers]]
  name = "tools"
  enable = true
[[layers]]
  name = "tags"
  enable = true
[[layers]]
  name = "tmux"
  enable = true
[[layers]]
  name = "lang#rust"
  enable = true
[[layers]]
  name = 'lang#go'
  enable = false
[[layers]]
  name = 'lang#javascript'
  enable = false
[[layers]]
  name = 'lang#typescript'
  enable = false
[[layers]]
  name = 'lang#python'
  enable = false
[[layers]]
  name = 'lang#html'
  enable = false
[[layers]]
  name = 'lang#markdown'
  enable = true
# The LSP layer does not work well for Rust,
#   it frequently errors (full screen) and crashes
[[layers]]
  name = "lsp"
  enable = true
  filetypes = [
    "rust",
    "javascript",
    "typescript"
  ]
  [layers.override_cmd]
    rust = ["rustup", "run", "stable", "rls"]
  [layers.override_cmd]
    typescript = ['javascript-typescript-stdio']
